import Foundation

public enum CorpusData {
    public static let allDocuments: [String] = [
        "Corpus/tex/whythisrenew.tex",
        "Corpus/tex/3gpt5.tex",
        "Corpus/tex/ufofrulesetreflect1.tex",
        "Corpus/tex/cli-output.tex",
        "Corpus/tex/IMO-2025-notes.tex",
        "Corpus/tex/tex3.tex",
        "Corpus/tex/tex2.tex",
        "Corpus/tex/IMO-2024-notes.tex",
        "Corpus/txt/File 2.txt",
        "Corpus/txt/integ20242025000.txt",
        "Corpus/txt/ufofruleset1.txt",
        "Corpus/txt/thoughtsufofrules1.txt",
        "Corpus/txt/tex2reflect.txt",
        "Corpus/txt/rule2025recalc1.txt",
        "Corpus/pdf/IMO-2025-notes-evanchen.pdf",
        "Corpus/pdf/imo-2.pdf",
        "Corpus/pdf/imo-3.pdf",
        "Corpus/pdf/imo-7.pdf",
        "Corpus/pdf/imo-6.pdf",
        "Corpus/pdf/imousa2025EC.pdf",
        "Corpus/pdf/imo-4.pdf",
        "Corpus/pdf/imo.pdf",
        "Corpus/pdf/imo-5.pdf",
        "Corpus/html/Using_Machine_Learning_and_Neural_Networks_to_Analyze_and_Predict_Chaos_in_Multi_Pendulum_and_Chaoti.html",
        "Corpus/sty/# A Hyper-Meta-Reconstruction: Synergizi.sty",
        "Corpus/sty/### Version 1: Extended Rewrite (Approxi.sty",
        "Corpus/md/tex-thoughts1.md",
        "Corpus/md/cursor_integration_of_deepmind_materialv1ff.md",
        "Corpus/md/tex1.md",
        "Corpus/md/reflection-why.md",
        "Corpus/md/ruleset20242025.md",
        "Corpus/md/thoughts1.md",
        "Corpus/md/cursor_upcoming_openai_livestream_event.md",
        "Corpus/md/thoughts0.md",
        "Corpus/md/outputs-current-oates.md",
        "Corpus/md/### Hyper-Meta Ruleset: Synthesizing Use.md",
        "Corpus/md/cursor_gpt5fast-thoughtsunincludedimo.md",
        "Corpus/md/cursor_integration_of_deepmind_material.md",
    ]
}

